spring.application.name=exam-jee-backend
spring.datasource.url=jdbc:mariadb://localhost:3306/ebanking?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
server.port=8000

app.jwt.secret=2gc3l7a0nxb13apfeb3ma9yyymu9awrj903lt8m51wzsrk7s27qywayht2usv2ju